# Generated by Django 3.2.5 on 2021-07-12 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_following_likes_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='users_being_followed',
        ),
        migrations.AddField(
            model_name='following',
            name='followers',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='following',
            name='following',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='following',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
