# Generated by Django 3.2.5 on 2021-07-21 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210712_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.AddField(
            model_name='likes',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
